name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  #Выберите нужную версию Python

      - name: Установка зависимостей
        run:
          python -m pip install --upgrade pip
          pip install pytest #Установите pytest, если используете его

      - name: Запуск тестов
        run:
          python -m unittest test_chet.py #Запуск тестов
