name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  #Выберите нужную версию Python

      - name: Установка зависимостей
        run:
          python -m pip install --upgrade pip
          pip install pytest

      - name: Запуск тестов
        run:
          python -m unittest test_even_odd.py #Запуск тестов
